### ISSUE TITLE
配置QQ登录回调host问题

### ISSUE THREAD

**Issue by zhangzh950730** [zq99299/spring-security#1]
请问用你这套QQ的开发账号,需要将回调host改为什么

**Comment by zq99299** [comment]
你用你自己的 qq 信息嘛。 我这个 qq 的信息是我不小心上传上来了。

如果要用我这个里面的 qq 信息的话，这个是笔记，你参考下 https://blog.csdn.net/mr_zhuqiang/article/details/81942563

**Comment by zq99299** [comment]
windows下hosts文件地址：C:\Windows\System32\drivers\etc

127.0.0.1 mrcode.cn
127.0.0.1 localhost

添加以上两个映射，保存文件

**Comment by zhangzh950730** [comment]
上次申请了没通过,我以为你这是测试的号码呢,我测试下代码就不用了 感谢
